import type { Metadata } from "next";
import { Familjen_Grotesk } from 'next/font/google';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const familjenGrotesk = Familjen_Grotesk({
  subsets: ['latin'],
  weight: ['400', '700'], // you can add other weights if you want
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={familjenGrotesk.className}>
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body> */}
      <body>{children}</body>
    </html>
  );
}
